### ISSUE TITLE
ltfc.net (signed tile URLs)

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#128]
using the below image as example, the site seems to encrypted their tile images. is this supported by dezoomify-rs? Thank you!

https://ltfc.net/img/606d793980afed71f101b2e3

**Comment by lovasoa** [comment]
The tiles are not encrypted, they are just signed.
You will have to read their javascript code and extract their signature function to port it to dezoomify. Nothing impossible, but there is some tedious work to do. If you are interested in doing that yourself, you can keep this issue open and create a PR. Otherwise, you can close this issue.

**Comment by lovasoa** [comment]
Here is their signing function, it's very simple:

```js
  encodeImageURL: function (a) {
    var b = a.match(URL_REG);
    if (!b) return a;
    var c = b[1],
    d = b[2],
    e = (b[3], b[4]),
    f = PG.CAG_HOST,
    g = 31536000 * Math.ceil((new Date).getTime() / 31536000000);
    g = g.toString(16);
    var h = f + encodeURI(d) + g,
    i = cag(h);
    return [c,
    d,
    '?',
    e,
    '&sign=',
    i,
    '&t=',
    g].join('')
  },
```

`cag` seems to just be the md5 function.

![image](https://user-images.githubusercontent.com/552629/116314014-d97e1900-a7ae-11eb-9d44-f1e3941b327a.png)

**Comment by tojoshuazhang** [comment]
Thank you @lovasoa for the explanation! I'll close this one as I don't have any coding experience.
