### ISSUE TITLE
There is a color difference between the downloaded image and the one on Google Art.

### ISSUE THREAD

**Issue by ngoncom** [lovasoa/dezoomify-rs#254]
Hi,

Recently, I noticed a color difference between the image on Google Art and the downloaded image, let see:

- Image on Google Art:
<img width="938" alt="1" src="https://github.com/user-attachments/assets/313fef3c-dc0c-4f3d-965f-26e52cfc6320">

(link: [https://artsandculture.google.com/asset/etude-pour-vers-le-bleu/1gH8RLY-nW279Q](https://artsandculture.google.com/asset/etude-pour-vers-le-bleu/1gH8RLY-nW279Q))

- Downloaded image:
![Wassily Kandinsky - Study for 'To The Blue' (c  1939)](https://github.com/user-attachments/assets/ffb6fca7-b85f-4174-80d7-4e32581766ef)

Thank you!

**Comment by lovasoa** [comment]
Zoom in on the Google art version. At max zoom, it should have the same color as what you downloaded. 

dezoomify-rs also lets you download the smaller versions (that have different colors) if you need.

**Comment by ngoncom** [comment]
> dezoomify-rs also lets you download the smaller versions (that have different colors) if you need.

I tried downloading from zoom level 1 to 4 but the pictures have different colors than on Google, can you help me review it?

**Comment by IGUPAYITI** [comment]
I found a color difference too while using dezoomify-rs but no with dezoomify web.
I have opened an issue there, with images for reference:
[https://github.com/lovasoa/dezoomify-rs/issues/259](url)

**Comment by ngoncom** [comment]
> I found a color difference too while using dezoomify-rs but no with dezoomify web. I have opened an issue there, with images for reference: [https://github.com/lovasoa/dezoomify-rs/issues/259](url)

Yes, i confirm that the web version is correct as on Google, but the Dezoomify-rs is not. Please see this:

<img width="941" alt="a" src="https://github.com/user-attachments/assets/120c44e1-70eb-4f15-baa1-98981ccf235a">

**Comment by lovasoa** [comment]
Do you see the issue even when exporting to the lossless png format ?

**Comment by lovasoa** [comment]
Should be fixed in 2.13

**Comment by ngoncom** [comment]
> Should be fixed in 2.13

I just tried v2.13 version but didn't see any difference, please help!

**Comment by IGUPAYITI** [comment]
Hello, I'm the user who opened the issue about the "Green Distortion" of the latest dezoomify-rs versions.
For me the latest version fixed it! Because I'm still in the midst of my art printing project for caution I again ran a test using the Getty website that also offers direct download. The two images were almost identical analyzed with Adobe Photoshop color histogram with the difference absolutely non noticeable to me:

Direct Download Color Histogram
Mean: 38.77
Standard Deviation: 39.66

Dezoomify-rs Color Histogram
Mean: 38.69
Standard Deviation: 39.77

I'm really no tech expert so maybe @lovasoa could run a better test... @ngoncom I can only advise you to try download in a lossless format like TIFF using -rs from the command prompt which is the method I've used.
I'm available for help, have a nice day.

**Comment by DigitalCurator** [comment]
I normalised your image's tint into 2 versions:
![IMG_5627](https://github.com/user-attachments/assets/7d218f1c-bc2a-496b-ba3d-58e00321beb4)


![IMG_5626](https://github.com/user-attachments/assets/aadf4d75-b923-4220-80a2-5b36ab60047d)

**Comment by DigitalCurator** [comment]
@ngoncom , I have normalized the image, here's the original, and 2 normalized versions.

Original (from the download):
![Kandinsky, Wassily; Study for  quot;To The Blue quot;; c  1939](https://github.com/user-attachments/assets/ce5ae94a-d703-4eb1-b6ac-91c4be10555e)

I normalized the tint in 2 versions:
![IMG_5629](https://github.com/user-attachments/assets/d67f0b7c-9f79-4394-89b2-f6debe93a0ec)

![IMG_5630](https://github.com/user-attachments/assets/670a8264-2b11-4db0-b09c-643890bdf6a3)

**Comment by ngoncom** [comment]
@IGUPAYITI : Actually I don't know how to download images like on Google website.

I see **dezoomify.ophir.dev** has done that very well, but dont know how to do it when using **dezoomify-rs**.

This is the image downloaded on **dezoomify.ophir.dev**, it's awesome:

![dezoomify.ophir.dev](https://github.com/user-attachments/assets/579af08c-80e6-4d2b-8f68-84250146e416)

And here is how I use **dezoomify-rs** to download:

<img width="592" alt="1" src="https://github.com/user-attachments/assets/949ba18d-f06a-42b2-8b9a-090c98412b00">

**Comment by IGUPAYITI** [comment]
Greetings @ngoncom, for running dezoomify through the Command Prompt drag dezoomify-rs.exe into the Command Prompt then type image URL and desired filename with quotation marks.
E.g.
C:\Users\ngoncom>C:\Users\ngoncom\Downloads\dezoomify-rs.exe "https://artsandculture.google.com/asset/etude-pour-vers-le-bleu/1gH8RLY-nW279Q" "Wassily Kandinsky, Study for To The Blue, 1939.tif"
Trying to change the output to a lossless format like .tif may solve the problem.
Also if you have an hard time finding image URLs other than Arts&Culture you can use the dezoomify browser extension which most of the times detects it automatically. For Chrome:
https://chromewebstore.google.com/detail/dezoomify/iapjjopjejpelnfdonefbffahmcndfbm
Hope it works, goodbye.

**Comment by ngoncom** [comment]
@IGUPAYITI:

I apologize for wasting your time, but I'm really not satisfied.

If you download it as **.tif**, the image size increases terribly (123 Mb for **.tif**, but only 2.77 Mb for **.jpg**). Meanwhile, the problem I care about is **the color**, it is still not solved (the color is not as beautiful as on Google).

**Comment by IGUPAYITI** [comment]
Dezoomify-rs it is not the problem, it is your image viewer program misinterpreting the data because of a missing color profile. Dezoomify-rs can't download attached color profile. Most of the times it is simply sRGB and your program display it correctly by default but sometimes it is a wider RGB (Adobe, ProPhoto etc.) and you need to try assigning different profiles yourself to find the one matching the online image. If not the image will appear highly desaturated.
In this case you should assign ProPhoto RGB.
You should have tried downloading other images to see if the problem was specific with your desired file because nine times out of ten the default online color profile is sRGB and there shouldn't have been any problem.

**Comment by DigitalCurator** [comment]
Correct. I suspect its your browser "hardware acceleration" setting causing the tinting color of the image rendered.
