### ISSUE TITLE
Issue with outfile format

### ISSUE THREAD

**Issue by SmithJustinL** [lovasoa/dezoomify-rs#267]
I am trying to use the command line to dezoomify an image with the outfile format of png. I keep getting the same error:

C:\Users\frate>dezoomify-rs [-l] [https://www.idaillinois.org/iiif/2/npl:10961/info.json] [dezoomified.png]
error: unexpected argument '[dezoomified.png]' found

Can anyone please tell me what exactly I am doing wrong here? Thanks.

**Comment by lovasoa** [comment]
The issue lies in how you are providing the arguments to the `dezoomify-rs` command. The square brackets (`[ ]`) in the error message suggest that the arguments are optional and should **not** be included in your command. Here's how to fix it:

### Correct Command Syntax
Try this:

```bash
dezoomify-rs -l https://www.idaillinois.org/iiif/2/npl:10961/info.json dezoomified.png
```

### Explanation
1. **Remove brackets (`[ ]`)**: Brackets are typically used in documentation to indicate optional arguments. You shouldn't include them in the actual command.
2. **Argument order**: The URL comes immediately after the options (`-l` in this case), followed by the output filename (`dezoomified.png`).
3. **Output format**: By specifying the output filename as `dezoomified.png`, the tool will save the image in PNG format.

Let me know if this works or if you're encountering further issues!
