### ISSUE TITLE
IIIF: unable to download images on servers that do not support the "default" quality

### ISSUE THREAD

**Issue by MrChrisWin** [lovasoa/dezoomify-rs#31]
Hello,
Could you help me to write the correct command for downloading from Yale Collection?

The IIIF viewer: https://collections.britishart.yale.edu/zoom/index.html?image=fd470c3e-ead0-4878-ac97-d63295753f82
The json path: https://images.britishart.yale.edu/iiif/fd470c3e-ead0-4878-ac97-d63295753f82/info.json

I tried the normal code, but it returns 400 Bad Request error:
`dezoomify-rs "https://images.britishart.yale.edu/iiif/fd470c3e-ead0-4878-ac97-d63295753f82/info.json"`

I then tried to put in the header of the viewer page but it still returns same error:
`dezoomify-rs -H "https://collections.britishart.yale.edu/zoom/index.html?image=fd470c3e-ead0-4878-ac97-d63295753f82"  "https://images.britishart.yale.edu/iiif/fd470c3e-ead0-4878-ac97-d63295753f82/info.json"`

The online dezoomify works fine with the json path, but I would like dezoomify-rs better for batch processing.

Thank you

**Comment by lovasoa** [comment]
Hello,
  You found a bug in dezoomify-rs. Thank you for reporting it ! I am going to work on a fix.

The problem is that dezoomify-rs always queries the "default" quality, which is not supported by the yale IIIF server : 

https://images.britishart.yale.edu/iiif/fd470c3e-ead0-4878-ac97-d63295753f82/4608,0,512,512/512,512/0/default.jpg

They support the "native" quality however : 

https://images.britishart.yale.edu/iiif/fd470c3e-ead0-4878-ac97-d63295753f82/4608,0,512,512/512,512/0/native.jpg

**Comment by lovasoa** [comment]
This is fixed :smiley: 

You'll be able to download the new release in the release section in a few minutes.

![dezoomified_1](https://user-images.githubusercontent.com/552629/77248695-a24c4880-6c3b-11ea-8b12-68d18f1e6934.jpg)

Thanks again for reporting the issue !

**Comment by MrChrisWin** [comment]
Thank you for the quick fix, lovasoa.
