### ISSUE TITLE
Test whether the image size fits the chosen file format before starting to download tiles

### ISSUE THREAD

**Issue by asoftbird** [lovasoa/dezoomify-rs#42]
I'm trying to download the newly uploaded [Nightwatch painting gigapixel image](http://hyper-resolution.org/Nightwatch) at level 1, which is about 5.6 gigapixels. (Level 0 is too large at 44.8 gigapixels).   
Level 1 is able to allocate enough RAM (about 49GB) and it downloaded the image tiles fully over the course of about 15 minutes.
However, upon completion of the download it threw this error:

![image](https://user-images.githubusercontent.com/45722355/81755602-833e9a00-94b9-11ea-86dd-2033aba11def.png)

I've got plenty of disk space and a total RAM size of 64GB (not including pagefile).  Is this image just too large or does it just need more RAM?

**Comment by MrChrisWin** [comment]
What is the URL you feed into dezoomify-rs?
What file format did you output to?
This seems really nice. Thanks for introducing it.

**Comment by MrChrisWin** [comment]
Come to think of it, jpeg limitation is 65000x65000 pixels. If any dimension is above that then it won't work. Try Tiff or png

**Comment by lovasoa** [comment]
Hello, 
  Indeed, the error comes from the fact that the JPEG file format limits the size of images in both dimensions to 65535 pixels. 
  However, dezoomify-rs should test whether whether the image fits immediately after the zoom level has been chosen, instead of first downloading all the tiles and then failing because the huge image that has been downloaded cannot be saved.

**Comment by asoftbird** [comment]
Is this info like max size per file format available anywhere? Wiki mentioned in the readme is empty and readme itself doesn't seem to contain anything on filesize(or supported file types) either.

**Comment by lovasoa** [comment]
The limitations are inherent to the file formats, not to the application producing the files. You can find the limitations, e.g. in the wikipedia articles of the file formats. The corrupted tif files are due to a bug in the image library that dezoomify-rs uses; I reported it there : https://github.com/image-rs/image/issues/1216

**Comment by asoftbird** [comment]
Thanks, I was able to get the file I need. It does seem to create compressed PNG files though, the output was 11GB but in Photoshop it took a good hour to open it, uncompressed it's apparently 30GB. Is there an option to export without compression?

**Comment by lovasoa** [comment]
Yes, you can export the image to BMP, which is an uncompressed image format.

**Comment by SeanEatsWorld** [comment]
I don't mean to hi-jack this thread but I need some help too. I'm inexperienced and frankly don't know what I'm doing. I don't even know how to properly use this website which is why I'm posting in here. 

I'm trying to download an image from artsy website for a personal project that I'm working on and they have their high resolution zoom images protected from downloading. I've opened up the view source and tried to find the image source in the HTML but found that they have hidden it pretty well. Can someone help me to see how I can locate the hidden zoom file (high res) that I can download? I tried dezoomify and that doesn't seem to work for me either. 

https://www.artsy.net/artwork/jonathan-lasker-scenic-reality

**Comment by CharlyAlonso** [comment]
Hello,
Right now I'm trying to go down in the penultimate level by quadrants:
dezoomify-rs.exe -r 3 tiles.yaml (B) .png
dezoomify-rs.exe -r 3 tiles.yaml (B) .png

url_template: "http://hyper-resolution.org/dzi/Rijksmuseum/SK-C-5/SK-C-5_VIS_20-um_2019-12-21_files/17/{{x/256}}_{{y/256}}.jpeg"

variables:
  - name: x
    from: 0
    to: 57856 # Image width, taken from stage 1
    step: 256 # Tile width, taken from stage 1

  - name: and
    from: 0
    to: 96875 # Image height
    step: 256 # Tile height

url_template: "http://hyper-resolution.org/dzi/Rijksmuseum/SK-C-5/SK-C-5_VIS_20-um_2019-12-21_files/17/{{x/256}}_{{y/256}}.jpeg"

variables:
  - name: x
    from: 58112
    to: 115625 # Image width, taken from stage 1
    step: 256 # Tile width, taken from stage 1

  - name: and
    from: 0
    to: 96875 # Image height
    step: 256 # Tile height

Later, I will try to join it with Photoshop and save it in PSB format

I'll tell ....

**Comment by lovasoa** [comment]
The latest version of dezoomify-rs tests whether the image size fits the file format before starting the downloads. I forgot to close this earlier.

https://github.com/lovasoa/dezoomify-rs/blob/master/src/output_file.rs#L17-L20
