### ISSUE TITLE
Need a specification of image qualities

### ISSUE THREAD

**Issue by s38383** [lovasoa/dezoomify-rs#68]
The IIIF server in Harvard University provides 4 image quality specifications: "default", "bitonal", "grey", "color".  But the quality of the downloaded images in dezoomify-rs is "gray", not the "color" one. The online version dezoomify doesn't have this problem.  It is useful to add an option to specify the quality of images in dezoomify-rs. Someone need "bitonal" images, while the most need "color" images. 
Thanks a lot!

**Comment by lovasoa** [comment]
Hi, and thank you for reporting this.
  The code [defines an order](https://github.com/lovasoa/dezoomify-rs/blob/master/src/iiif/tile_info.rs#L46-L47) of preferences for image qualities, and "default" is supposed to always be chosen when it's available. Do you have a link to the image in question ?

  In the meantime, a workaround is to simply download the info.json locally, edit it, and launch dezoomify-rs on your local version.

**Comment by s38383** [comment]
The 'info.json' files like this: https://ids.lib.harvard.edu/ids/iiif/54059020/info.json

**Comment by lovasoa** [comment]
Ok, the problem is not what it looks like. The tiles are requested with the "default" quality in the "webp" format. But the webp decoder we use supports only the luma channel of images: https://github.com/image-rs/image/issues/939

I am going to move down webp in the priority list so that other formats are chosen when they are available.
